#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| オートローダー登録
|--------------------------------------------------------------------------
|
| コンポーサーは自動的に生成する便利なクラスローダーをアプリケーションに
| 提供しています。私達はそれを利用するだけです！そのスクリプトを
| ここで読み込んでいるので、「手動」によりクラスをロードすることに
| 心を煩わせる必要はありません。リラックスしていましょう。
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Artisanアプリケーション実行
|--------------------------------------------------------------------------
|
| コンソールアプリケーションを実行する時には、コンソールの中で現在の
| CLIコマンドが実行され、レスポンスが端末か開発者の他の出力装置に
| 送られます。それだけです！
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| アプリケーションのシャットダウン
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| 後片付けをしてもらうため、シャットダウンイベントを発行します。
| これはリクエストの一番最後に実行されます。
|
*/

$kernel->terminate($input, $status);

exit($status);
